### ISSUE TITLE
demo site is broken

### ISSUE THREAD

**Issue by dmerc** [wix/wix-ui-lib#88]
accessing demo site over HTTPS results in these errors on chrome and firefox, and most demo widgets are not working.

![screenshot from 2015-02-16 19 46 39](https://cloud.githubusercontent.com/assets/2751776/6216644/a4d0df7c-b614-11e4-85e4-217c95eade77.png)

**Comment by liors** [comment]
@dmerc site demo does not support https. please use http://wix.github.io/wix-ui-lib/
